-- Ingest API (7.4, build-spec-v3 § 4.3, § 6). Tokens for the CS Sync Skill
-- (and later the chat agent / file import, § 4.6) to call the `ingest`
-- Edge Function — a completely different auth model from `provisioning`
-- (a bearer token, not a Supabase user session), so it needs its own
-- credential table rather than anything in auth.*.

create table public.ingest_tokens (
  id              uuid primary key default gen_random_uuid(),
  label           text not null,
  token_hash      text not null unique,          -- SHA-256 hex of the plaintext; plaintext is never stored
  allowed_org_ids uuid[],                         -- null = unrestricted (every account)
  created_by      uuid references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now(),
  expires_at      timestamptz not null,           -- required; capped at 365 days by the issuing function, not here
  revoked_at      timestamptz,
  last_used_at    timestamptz
);

alter table public.ingest_tokens enable row level security;

create policy ingest_tokens_select on public.ingest_tokens
  for select to authenticated using (public.is_super_admin());
-- Deliberately NO insert/update policy for `authenticated` at all — a
-- token's plaintext only ever exists for one response, generated by the
-- provisioning Edge Function's create_ingest_token action (service role,
-- bypasses RLS). Revocation is the same action's sibling, not a direct
-- client UPDATE. This is credential material, not a CS record — no audit
-- trigger either (nothing sensitive is logged, see provisioning's
-- writeAudit calls for this table, which carry only id/label).

grant select on public.ingest_tokens to authenticated, service_role;
grant insert, update on public.ingest_tokens to service_role;

-- Traceability (D-0xx, go-ahead point 4): every run and every proposal the
-- ingest endpoint creates can be traced back to the exact token that made
-- it. Both nullable — nothing else sets these.
alter table public.sync_runs add column ingest_token_id uuid references public.ingest_tokens(id) on delete set null;
alter table public.proposals add column ingest_token_id uuid references public.ingest_tokens(id) on delete set null;

-- Race safety (go-ahead point 8): two overlapping ingest runs (a Refresh
-- click racing the daily job, or two daily-job retries) must not both
-- create a new pending proposal for the same (account, table, source_ref).
-- The ingest function's own SELECT-then-INSERT is the common-path check;
-- this index is the authoritative backstop — a 23505 on insert means
-- "someone else already filed this, go merge into theirs instead."
create unique index proposals_pending_dedupe
  on public.proposals (org_id, target_table, source_ref)
  where status = 'pending' and source_ref is not null;
